// This file is auto-generated by Convex.
// This is a placeholder to simulate the generated API file.

import type { FunctionReference } from "convex/server"

export const api = {
  auth: {
    registerUser: {} as FunctionReference<
      "mutation",
      { email: string; name: string; tenantId: string; authProviderId: string; role?: string },
      { userId: string }
    >,
    getUserProfile: {} as FunctionReference<"query", { userId: string }, any>,
    validateTenantAccess: {} as FunctionReference<"query", { userId: string; tenantId: string }, boolean>,
    validateUserRole: {} as FunctionReference<"query", { userId: string; requiredRoles: string[] }, boolean>,
  },
}
